# ref:
# https://docs.github.com/en/actions/quickstart
# https://github.com/google/yapf/blob/main/.github/workflows/ci.yml
# https://github.com/psf/black/blob/main/.github/workflows/test.yml

name: Test

on:
  push:
    paths-ignore:
      - "scripts/**"
      - "*.md"

  pull_request:
    paths-ignore:
      - "scripts/**"
      - "*.md"


jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    # - name: Lint with flake8
    #   run: |
    #     python -m pip install toml flake8
    #     flake8 . --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest
